/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer clientId;
    private String clientcode;

    public Client() {}

    public Client(Client value) {
        this.clientId = value.clientId;
        this.clientcode = value.clientcode;
    }

    public Client(
        Integer clientId,
        String clientcode
    ) {
        this.clientId = clientId;
        this.clientcode = clientcode;
    }

    /**
     * Getter for <code>public.client.client_id</code>.
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>public.client.client_id</code>.
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for <code>public.client.clientcode</code>.
     */
    public String getClientcode() {
        return this.clientcode;
    }

    /**
     * Setter for <code>public.client.clientcode</code>.
     */
    public void setClientcode(String clientcode) {
        this.clientcode = clientcode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Client other = (Client) obj;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.clientcode == null) {
            if (other.clientcode != null)
                return false;
        }
        else if (!this.clientcode.equals(other.clientcode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.clientcode == null) ? 0 : this.clientcode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Client (");

        sb.append(clientId);
        sb.append(", ").append(clientcode);

        sb.append(")");
        return sb.toString();
    }
}
