/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao;


import adrianwudev.driverhelper.Jooq.Dao.tables.FlywaySchemaHistory;
import adrianwudev.driverhelper.Jooq.Dao.tables.Orders;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_ORDERS_ISEXCEPTION = Internal.createIndex(DSL.name("idx_orders_isexception"), Orders.ORDERS, new OrderField[] { Orders.ORDERS.IS_EXCEPTION }, false);
    public static final Index IDX_ORDERS_WEEKDAY = Internal.createIndex(DSL.name("idx_orders_weekday"), Orders.ORDERS, new OrderField[] { Orders.ORDERS.WEEKDAY }, false);
    public static final Index IDX_ORDERS_WEEKDAY_ISEXCEPTION = Internal.createIndex(DSL.name("idx_orders_weekday_isexception"), Orders.ORDERS, new OrderField[] { Orders.ORDERS.WEEKDAY, Orders.ORDERS.IS_EXCEPTION }, false);
}
