/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao;


import adrianwudev.driverhelper.Jooq.Dao.tables.FlywaySchemaHistory;
import adrianwudev.driverhelper.Jooq.Dao.tables.Orders;
import adrianwudev.driverhelper.Jooq.Dao.tables.Test;
import adrianwudev.driverhelper.Jooq.Dao.tables.records.FlywaySchemaHistoryRecord;
import adrianwudev.driverhelper.Jooq.Dao.tables.records.OrdersRecord;
import adrianwudev.driverhelper.Jooq.Dao.tables.records.TestRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<OrdersRecord> ORDERS_PKEY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("orders_pkey"), new TableField[] { Orders.ORDERS.ORDER_ID }, true);
    public static final UniqueKey<TestRecord> TEST_PKEY = Internal.createUniqueKey(Test.TEST, DSL.name("test_pkey"), new TableField[] { Test.TEST.ID }, true);
}
