/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao;


import adrianwudev.driverhelper.Jooq.Dao.tables.Client;
import adrianwudev.driverhelper.Jooq.Dao.tables.FlywaySchemaHistory;
import adrianwudev.driverhelper.Jooq.Dao.tables.Orders;
import adrianwudev.driverhelper.Jooq.Dao.tables.Test;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.client</code>.
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.test</code>.
     */
    public final Test TEST = Test.TEST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Client.CLIENT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Orders.ORDERS,
            Test.TEST
        );
    }
}
