/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao;


import adrianwudev.driverhelper.Jooq.Dao.tables.Client;
import adrianwudev.driverhelper.Jooq.Dao.tables.FlywaySchemaHistory;
import adrianwudev.driverhelper.Jooq.Dao.tables.Orders;
import adrianwudev.driverhelper.Jooq.Dao.tables.Test;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.test</code>.
     */
    public static final Test TEST = Test.TEST;
}
