/*
 * This file is generated by jOOQ.
 */
package adrianwudev.driverhelper.Jooq.Dao.tables.records;


import adrianwudev.driverhelper.Jooq.Dao.tables.Client;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends TableRecordImpl<ClientRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client.client_id</code>.
     */
    public void setClientId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.client.clientcode</code>.
     */
    public void setClientcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client.clientcode</code>.
     */
    public String getClientcode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.CLIENT_ID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.CLIENTCODE;
    }

    @Override
    public Integer component1() {
        return getClientId();
    }

    @Override
    public String component2() {
        return getClientcode();
    }

    @Override
    public Integer value1() {
        return getClientId();
    }

    @Override
    public String value2() {
        return getClientcode();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setClientId(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setClientcode(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer clientId, String clientcode) {
        super(Client.CLIENT);

        setClientId(clientId);
        setClientcode(clientcode);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(adrianwudev.driverhelper.Jooq.Dao.tables.pojos.Client value) {
        super(Client.CLIENT);

        if (value != null) {
            setClientId(value.getClientId());
            setClientcode(value.getClientcode());
            resetChangedOnNotNull();
        }
    }
}
