version: '3'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
    container_name: driver-helper-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-driver
