# PostgreSQL
spring:
  datasource:
#    docker ip: 192.168.0.13
#    url: jdbc:postgresql://localhost:9040/driver # local
    url: jdbc:postgresql://192.168.0.13:9040/driver # docker
    username: adrian
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: "classpath:db/migration"

flyway:
  validate-on-migrate: false
  encoding: UTF8MB4
  out-of-order: true

order:
  default:
    page: 1
    page-size:  50