# PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://postgres-driver:5432/driver
#    url: jdbc:postgresql://172.22.128.1:9040/driver
    username: adrian
    password: password
    driver-class-name: org.postgresql.Driver

#  *** In order to start flyway before JOOQ, move flyway to plugin section ***
#  flyway:
#    locations: "classpath:db/migration"
#
#flyway:
#  validate-on-migrate: false
#  encoding: UTF8MB4
#  out-of-order: true

order:
  default:
    page: 1
    page-size:  10
